### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by SametSahin10** [ajinasokan/flutter_fgbg#1]
Hello, I'm using your package on my app. Do you have any plans to support null safety?

**Comment by ajinasokan** [comment]
Yes. Working on it now

**Comment by ajinasokan** [comment]
@SametSahin10 Can you try with:

```
flutter_fgbg: ^0.1.0
```

**Comment by SametSahin10** [comment]
It looks like you've made it.

![Screenshot from 2021-03-04 15-42-27](https://user-images.githubusercontent.com/29546660/109965699-62715a80-7d00-11eb-832b-fe507e3b50ba.png)

`dart pub outdated --mode=null-safety` shows that the version `0.1.0` supports null safety. Thanks for the quick response. Have a good day.
