### ISSUE TITLE
Listener not firing upon going to background/foreground

### ISSUE THREAD

**Issue by gummz** [ajinasokan/flutter_fgbg#20]
Hi,

I created a listener here:

`class Notifier extends ChangeNotifier {
  late StreamSubscription<FGBGType>? _subscription;

  Notifier() {
    _subscription = FGBGEvents.instance.stream.listen((event) {
      logDebug('FGBG event: $event');
      if (event == FGBGType.foreground) {
        logDebug('event is foreground');
      }
    });
  }`

and this notifier doesn't seem to dispatch the events when I bring the app the background or foreground. I'm using Android Emulator, Pixel 6 Pro API 34

**Comment by ajinasokan** [comment]
Could you run the example project from the master branch and see if you are able see the logs?

I tried in an API 34 phone and it seems fine.

**Comment by gummz** [comment]
Thanks for the reply. I ran the example project and it indeed works, but as far as I can tell it's not using the stream directly but the widget FGBGNotifier. If I add my code to the example:

```
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _subscription = FGBGEvents.instance.stream.listen((event) {
      print('FGBG event: $event');
      if (event == FGBGType.foreground) {
        print('event is foreground');
      }
    });
  }
```

the event doesn't fire, although the original event from the FGBGNotifier still fires.

**Comment by gummz** [comment]
But I don't really need the stream explicitly. It's working perfectly with the widget.

**Comment by ajinasokan** [comment]
I just tried the snippet you had given and it seems to work in the master. Keep in mind that it will take a moment for the Android app to report the background switch.

I will close this for now. If you managed to reproduce the issue feel free to reopen with a sample main.dart.
