### ISSUE TITLE
fbgb listener not working when shouldAttachEngineToActivity overriden

### ISSUE THREAD

**Issue by qeepcologne** [ajinasokan/flutter_fgbg#26]
i am listening to fbgb events in main app state like that:
´´´
    fgbgListener = FGBGEvents.instance.stream.listen((event) {
      _logger.t("fbgb event: ${event.name}");
     });
´´´
this works fine, until i Override
shouldAttachEngineToActivity() with false
in MyActivity extends FlutterActivity.

use case for fbgb is to ask for pin code when app is resumed from minimized.
why do i override the shouldAttachEngineToActivity? Otherwise Activity is destroyed and recreated when i opening fcm (even if cached instance is used and app is in foreground).

similar listeners like didChangeAppLifecycleState still working.

**Comment by ajinasokan** [comment]
Not sure about `shouldAttachEngineToActivity` but just by the name it seems it disables plugin's ability to attach to activity. Then it won't be able to get the context so plugin cant initialize `ProcessLifecycleOwner` for the events.

**Comment by qeepcologne** [comment]
thanks for the answer.
Issue no longer relevant: removed shouldAttachEngineToActivity and replace with launchMode="singleInstance"
