### ISSUE TITLE
Is only one subscription allowed?

### ISSUE THREAD

**Issue by itaispector** [ajinasokan/flutter_fgbg#8]
Hi there,
I'm trying to connect to the stream from 2 different points in my app, It seems like the last one to connect has the stream flowing into it, and the other one does not.
Am I doing something wrong or this is by design?
Thanks

**Comment by robertherber** [comment]
Same issue here 👍

**Comment by ajinasokan** [comment]
This was fixed in #7. I will make a release with it.

**Comment by ajinasokan** [comment]
Try `flutter_fgbg: ^0.2.1`

**Comment by itaispector** [comment]
> Try `flutter_fgbg: ^0.2.1`

Thanks!  although before you made the fix, I ended up wrapping your lib with a class with a value notifier. I will test your release, if it's working well i'll dispose my wrapper
